services:
  # The Django Backend Web Service
  - type: web
    name: ecofeast-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: ML_API_URL
        value: http://ecofeast-ml-api:8001/predict
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: ecofeast-db
          property: connectionString

  # The FastAPI ML API Web Service
  - type: web
    name: ecofeast-ml-api
    env: python
    rootDir: ml_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8001
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  # The PostgreSQL Database
  - name: ecofeast-db
    databaseName: ecofeast
    user: ecofeast_user
